apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: passive-trout-nodejs 
  janus-idp.io/tekton: passive-trout-nodejs
  backstage.io/kubernetes-id: passive-trout-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: passive-trout-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  