apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: passive-trout-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: passive-trout-nodejs 
  name: passive-trout-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: passive-trout-nodejs 
